### ISSUE TITLE
smarty

### ISSUE THREAD

**Issue by Neeke** [sillydong/CZD_Yaf_Extension#1]
为什么的要用smarty呢？

**Comment by Neeke** [comment]
我的意思是，smary性能如此之低，而且语法很不友好。

**Comment by sillydong** [comment]
主要是因为smarty比较普遍，可以在BOOTSTRAP里面initView那段进行修改，不用smarty。而且这样不用在module的controller中设置setViewpath

**Comment by Neeke** [comment]
我可以理解为使用习惯吗？
其实你所说的“在controller中设置setViewPath”也可以很好地处理，这并不是使用smarty的一个条件。

2014-03-17 9:38 GMT+08:00 Chen Zhidong notifications@github.com:

**Comment by sillydong** [comment]
setViewPath是因为在使用smarty的时候，module下面的controller不能默认读到该module下的view，路径有问题，所以需要手动setViewPath。不使用smarty是不需要手动设置的，会自己去取该module下对应controller的action的view。

**Comment by mickeyouyou** [comment]
为什么不把数据库一起放出来呢？真心的

**Comment by sillydong** [comment]
@mickeyouyou 因为其实数据库没有什么内容，包括model里面Sample只是做一个示例。不过既然大家想要数据库，我就提交一个吧

**Comment by mickeyouyou** [comment]
very beautiful~
