### ISSUE TITLE
不用 命名空间的话在loader.php 中做何修改了？

### ISSUE THREAD

**Issue by TheDanielChen** [sillydong/CZD_Yaf_Extension#3]
不用 命名空间的话在loader.php 中做何修改了？

**Comment by sillydong** [comment]
@cstopery framework是集成了github上一个开源的将yaf用php表达的项目，旨在兼容虚拟空间无法安装yaf扩展的情况，具体可以上https://github.com/mzsolti/yaf-phpport看看
