### ISSUE TITLE
library根目录下是不是忘了添加Db.php

### ISSUE THREAD

**Issue by veking** [sillydong/CZD_Yaf_Extension#4]
Warning: Yaf_Loader::autoload(): Failed opening script G:\work/application\library\Db.php: No such file or directory in G:\work\application\library\Object.php on line 27

**Comment by sillydong** [comment]
Db.php在/library/Db/Db.php下

**Comment by veking** [comment]
Db目录下有这个文件，但是默认加载路径却是 library/Db.php，自动加载错误？还是文件丢失？

**Comment by sillydong** [comment]
在/application/Bootstrap.php的_initDatabase()下有这段

```
    Yaf_Loader::import(APPLICATION_PATH . '/library/Db/Db.php');
    Yaf_Loader::import(APPLICATION_PATH . '/library/Db/DbQuery.php');
```

你是不是没有加载boostrap或者initdatabase没执行

**Comment by veking** [comment]
Bootstrap文件被修改过，不是默认的，所以没import……
thanks！
